---
- hosts: all
  become: true
  vars:
    - github_account: Android60-projects
    - runner_org: yes
    - runner_user: gitlab-runner
  # - runner_state: "absent"
    - runner_labels:
        - virtualbox
        - molecule
    # - user_management:
    #   - name: github_runner_user
  roles:
    # - role: monolithprojects.user_management
    - role: monolithprojects.github_actions_runner

  pre_tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'